from __future__ import annotations

from typing import Protocol, runtime_checkable

from bespokelabs.sandbox.types import FileInfo, SandboxConfig, SandboxResult, SnapshotInfo


@runtime_checkable
class SandboxBackend(Protocol):
    def create(self, config: SandboxConfig) -> None: ...
    def execute_code(self, code: str, language: str) -> SandboxResult: ...
    def execute_command(self, command: str, args: list[str] | None) -> SandboxResult: ...
    def list_files(self, path: str) -> list[FileInfo]: ...
    def read_file(self, path: str) -> bytes: ...
    def write_file(self, path: str, content: bytes | str) -> None: ...
    def upload_file(self, local_path: str, remote_path: str) -> None: ...
    def download_file(self, remote_path: str, local_path: str) -> None: ...
    def snapshot(self) -> SnapshotInfo: ...
    def destroy(self) -> None: ...
